// Suppressir warning de React 19 en Ant Design
import "./init-warnings.js";

// Ant Design compatibility patch for React 19 - must be imported before any antd styles
import "@ant-design/v5-patch-for-react-19";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Ant Design styles
import "antd/dist/reset.css";
import AntdProvider from "./providers/AntdProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Estadísticas de Aforos Macro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdProvider>
          {children}
        </AntdProvider>
      </body>
    </html>
  );
}
